package com.orthoflow.voice.infrastructure.summary;

import lombok.Getter;
import lombok.Setter;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

/**
 * The end-of-consultation narrative summary.
 *
 * <p>Distinct from {@code GET /voice/sessions/{id}/summary}, which reads the
 * clinical tables back and is not generated by anything. This is the prose a
 * doctor reads at review — "Examen du 7 septembre : carie récurrente sur 16…"
 * — and it is generated, which is why it is off by default and why nothing it
 * produces is ever written to a clinical record without the doctor editing and
 * saving it themselves.
 *
 * <p>Any OpenAI-compatible chat endpoint works. The default targets Groq,
 * which is where the deployment already holds a key, and the default model is
 * a 70B-class one on purpose: a summary runs once per consultation, so latency
 * is irrelevant and the smaller models' French degrades noticeably on medical
 * vocabulary.
 */
@Component
@ConfigurationProperties(prefix = "orthoflow.voice.summary")
@Getter
@Setter
public class VoiceSummaryProperties {

    /**
     * When false, {@code POST /voice/sessions/{id}/summarize} answers 200 with
     * an empty summary and {@code error: "summary-disabled"}. The review page
     * still works — the doctor gets the structured findings and writes their
     * own observation — so this degrades rather than blocks.
     */
    private boolean enabled = false;

    /** Reported in the response and the log; the endpoint shape is fixed. */
    private String provider = "groq";

    private String apiKey = "";

    private String model = "llama-3.3-70b-versatile";

    /** OpenAI-compatible chat root, no trailing slash. */
    private String baseUrl = "https://api.groq.com/openai/v1";

    /**
     * Consultations are short and a summary is not a reasoning task, but a
     * long examination produces a lot of audit rows, so this is more generous
     * than the NLU's equivalent.
     */
    private int timeoutMs = 30000;

    private int maxOutputTokens = 1200;

    /**
     * The output language, as a full language name the model will recognise.
     * French because that is what the clinicians using this speak; an English
     * or Arabic deployment sets it here rather than editing the prompt.
     */
    private String language = "French";

    /**
     * Ceiling on how many audited commands are fed to the model. A session
     * past this is truncated to the most recent, with the prompt saying so —
     * a summary of most of a consultation beats a timeout.
     */
    private int maxCommands = 200;
}
